# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 636)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_20 = QtWidgets.QWidget(self.tab_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tab0_hwndlineEdit = QtWidgets.QLineEdit(self.widget_20)
        self.tab0_hwndlineEdit.setObjectName("tab0_hwndlineEdit")
        self.horizontalLayout_14.addWidget(self.tab0_hwndlineEdit)
        self.tab0_bindWinpushButton = QtWidgets.QPushButton(self.widget_20)
        self.tab0_bindWinpushButton.setObjectName("tab0_bindWinpushButton")
        self.horizontalLayout_14.addWidget(self.tab0_bindWinpushButton)
        self.tab0_showLogpushButton = QtWidgets.QPushButton(self.widget_20)
        self.tab0_showLogpushButton.setObjectName("tab0_showLogpushButton")
        self.horizontalLayout_14.addWidget(self.tab0_showLogpushButton)
        self.verticalLayout_13.addWidget(self.widget_20)
        self.splitter = QtWidgets.QSplitter(self.tab_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.groupBox_5 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_17 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_9.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_15 = QtWidgets.QWidget(self.widget_17)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tab0_threadRefleshpushButton = QtWidgets.QPushButton(self.widget_15)
        self.tab0_threadRefleshpushButton.setObjectName("tab0_threadRefleshpushButton")
        self.horizontalLayout_12.addWidget(self.tab0_threadRefleshpushButton)
        self.tab0_threadSavepushButton = QtWidgets.QPushButton(self.widget_15)
        self.tab0_threadSavepushButton.setObjectName("tab0_threadSavepushButton")
        self.horizontalLayout_12.addWidget(self.tab0_threadSavepushButton)
        self.tab0_threadAddpushButton = QtWidgets.QPushButton(self.widget_15)
        self.tab0_threadAddpushButton.setObjectName("tab0_threadAddpushButton")
        self.horizontalLayout_12.addWidget(self.tab0_threadAddpushButton)
        self.tab0_threadDelpushButton = QtWidgets.QPushButton(self.widget_15)
        self.tab0_threadDelpushButton.setObjectName("tab0_threadDelpushButton")
        self.horizontalLayout_12.addWidget(self.tab0_threadDelpushButton)
        self.verticalLayout_9.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.widget_17)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tab0_mainThreadtableView = QtWidgets.QTableView(self.widget_16)
        self.tab0_mainThreadtableView.setObjectName("tab0_mainThreadtableView")
        self.verticalLayout_8.addWidget(self.tab0_mainThreadtableView)
        self.tab0_detailThreadtableView = QtWidgets.QTableView(self.widget_16)
        self.tab0_detailThreadtableView.setObjectName("tab0_detailThreadtableView")
        self.verticalLayout_8.addWidget(self.tab0_detailThreadtableView)
        self.verticalLayout_9.addWidget(self.widget_16)
        self.verticalLayout_12.addWidget(self.widget_17)
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_19 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_18 = QtWidgets.QWidget(self.widget_19)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tab0_missionRefleshpushButton = QtWidgets.QPushButton(self.widget_18)
        self.tab0_missionRefleshpushButton.setObjectName("tab0_missionRefleshpushButton")
        self.horizontalLayout_13.addWidget(self.tab0_missionRefleshpushButton)
        self.tab0_missionMidpushButton = QtWidgets.QPushButton(self.widget_18)
        self.tab0_missionMidpushButton.setText("")
        self.tab0_missionMidpushButton.setObjectName("tab0_missionMidpushButton")
        self.horizontalLayout_13.addWidget(self.tab0_missionMidpushButton)
        self.tab0_missionRightpushButton = QtWidgets.QPushButton(self.widget_18)
        self.tab0_missionRightpushButton.setText("")
        self.tab0_missionRightpushButton.setObjectName("tab0_missionRightpushButton")
        self.horizontalLayout_13.addWidget(self.tab0_missionRightpushButton)
        self.verticalLayout_10.addWidget(self.widget_18)
        self.tab0_missiontableView = QtWidgets.QTableView(self.widget_19)
        self.tab0_missiontableView.setObjectName("tab0_missiontableView")
        self.verticalLayout_10.addWidget(self.tab0_missiontableView)
        self.verticalLayout_11.addWidget(self.widget_19)
        self.verticalLayout_13.addWidget(self.splitter)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_1)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_21 = QtWidgets.QWidget(self.groupBox_6)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_16.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_22 = QtWidgets.QWidget(self.widget_21)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tab1_missionRefleshpushButton = QtWidgets.QPushButton(self.widget_22)
        self.tab1_missionRefleshpushButton.setObjectName("tab1_missionRefleshpushButton")
        self.horizontalLayout_15.addWidget(self.tab1_missionRefleshpushButton)
        self.tab1_missionSavepushButton = QtWidgets.QPushButton(self.widget_22)
        self.tab1_missionSavepushButton.setObjectName("tab1_missionSavepushButton")
        self.horizontalLayout_15.addWidget(self.tab1_missionSavepushButton)
        self.tab1_missionAddpushButton = QtWidgets.QPushButton(self.widget_22)
        self.tab1_missionAddpushButton.setObjectName("tab1_missionAddpushButton")
        self.horizontalLayout_15.addWidget(self.tab1_missionAddpushButton)
        self.tab1_missionDelpushButton = QtWidgets.QPushButton(self.widget_22)
        self.tab1_missionDelpushButton.setObjectName("tab1_missionDelpushButton")
        self.horizontalLayout_15.addWidget(self.tab1_missionDelpushButton)
        self.verticalLayout_16.addWidget(self.widget_22)
        self.widget_23 = QtWidgets.QWidget(self.widget_21)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tab1_mainMissiontableView = QtWidgets.QTableView(self.widget_23)
        self.tab1_mainMissiontableView.setObjectName("tab1_mainMissiontableView")
        self.verticalLayout_17.addWidget(self.tab1_mainMissiontableView)
        self.tab1_detailMissiontableView = QtWidgets.QTableView(self.widget_23)
        self.tab1_detailMissiontableView.setObjectName("tab1_detailMissiontableView")
        self.verticalLayout_17.addWidget(self.tab1_detailMissiontableView)
        self.verticalLayout_16.addWidget(self.widget_23)
        self.verticalLayout_15.addWidget(self.widget_21)
        self.groupBox_7 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_18.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_24 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_25 = QtWidgets.QWidget(self.widget_24)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tab1_funRefleshpushButton = QtWidgets.QPushButton(self.widget_25)
        self.tab1_funRefleshpushButton.setObjectName("tab1_funRefleshpushButton")
        self.horizontalLayout_16.addWidget(self.tab1_funRefleshpushButton)
        self.tab1_funMidpushButton = QtWidgets.QPushButton(self.widget_25)
        self.tab1_funMidpushButton.setText("")
        self.tab1_funMidpushButton.setObjectName("tab1_funMidpushButton")
        self.horizontalLayout_16.addWidget(self.tab1_funMidpushButton)
        self.tab1_funRightpushButton = QtWidgets.QPushButton(self.widget_25)
        self.tab1_funRightpushButton.setText("")
        self.tab1_funRightpushButton.setObjectName("tab1_funRightpushButton")
        self.horizontalLayout_16.addWidget(self.tab1_funRightpushButton)
        self.verticalLayout_19.addWidget(self.widget_25)
        self.tab1_funtableView = QtWidgets.QTableView(self.widget_24)
        self.tab1_funtableView.setObjectName("tab1_funtableView")
        self.verticalLayout_19.addWidget(self.tab1_funtableView)
        self.verticalLayout_18.addWidget(self.widget_24)
        self.verticalLayout_25.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(10)
        self.splitter_3.setObjectName("splitter_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_20.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_20.setSpacing(5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_26 = QtWidgets.QWidget(self.groupBox_8)
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_21.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_27 = QtWidgets.QWidget(self.widget_26)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tab2_funRefleshpushButton = QtWidgets.QPushButton(self.widget_27)
        self.tab2_funRefleshpushButton.setObjectName("tab2_funRefleshpushButton")
        self.horizontalLayout_17.addWidget(self.tab2_funRefleshpushButton)
        self.tab2_funSavepushButton = QtWidgets.QPushButton(self.widget_27)
        self.tab2_funSavepushButton.setObjectName("tab2_funSavepushButton")
        self.horizontalLayout_17.addWidget(self.tab2_funSavepushButton)
        self.tab2_funAddpushButton = QtWidgets.QPushButton(self.widget_27)
        self.tab2_funAddpushButton.setObjectName("tab2_funAddpushButton")
        self.horizontalLayout_17.addWidget(self.tab2_funAddpushButton)
        self.tab2_funDelpushButton = QtWidgets.QPushButton(self.widget_27)
        self.tab2_funDelpushButton.setObjectName("tab2_funDelpushButton")
        self.horizontalLayout_17.addWidget(self.tab2_funDelpushButton)
        self.verticalLayout_21.addWidget(self.widget_27)
        self.widget_28 = QtWidgets.QWidget(self.widget_26)
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(5)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tab2_mainFuntableView = QtWidgets.QTableView(self.widget_28)
        self.tab2_mainFuntableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tab2_mainFuntableView.setObjectName("tab2_mainFuntableView")
        self.verticalLayout_22.addWidget(self.tab2_mainFuntableView)
        self.tab2_detailFuntableView = QtWidgets.QTableView(self.widget_28)
        self.tab2_detailFuntableView.setObjectName("tab2_detailFuntableView")
        self.verticalLayout_22.addWidget(self.tab2_detailFuntableView)
        self.verticalLayout_21.addWidget(self.widget_28)
        self.verticalLayout_20.addWidget(self.widget_26)
        self.groupBox_9 = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_23.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_23.setSpacing(5)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.widget_29 = QtWidgets.QWidget(self.groupBox_9)
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_29)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_30 = QtWidgets.QWidget(self.widget_29)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(2)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.tab2_nodeRefleshpushButton = QtWidgets.QPushButton(self.widget_30)
        self.tab2_nodeRefleshpushButton.setObjectName("tab2_nodeRefleshpushButton")
        self.horizontalLayout_18.addWidget(self.tab2_nodeRefleshpushButton)
        self.tab2_nodeDelpushButton = QtWidgets.QPushButton(self.widget_30)
        self.tab2_nodeDelpushButton.setObjectName("tab2_nodeDelpushButton")
        self.horizontalLayout_18.addWidget(self.tab2_nodeDelpushButton)
        self.verticalLayout_24.addWidget(self.widget_30)
        self.tab2_nodetableView = QtWidgets.QTableView(self.widget_29)
        self.tab2_nodetableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab2_nodetableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tab2_nodetableView.setObjectName("tab2_nodetableView")
        self.verticalLayout_24.addWidget(self.tab2_nodetableView)
        self.verticalLayout_23.addWidget(self.widget_29)
        self.verticalLayout_26.addWidget(self.splitter_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 340, 150))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_8)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.tab3_mouseXlineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.tab3_mouseXlineEdit.setObjectName("tab3_mouseXlineEdit")
        self.horizontalLayout_4.addWidget(self.tab3_mouseXlineEdit)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.tab3_mouseYlineEdit = QtWidgets.QLineEdit(self.widget)
        self.tab3_mouseYlineEdit.setObjectName("tab3_mouseYlineEdit")
        self.horizontalLayout_3.addWidget(self.tab3_mouseYlineEdit)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.tab3_mouseDelaylineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.tab3_mouseDelaylineEdit.setObjectName("tab3_mouseDelaylineEdit")
        self.horizontalLayout.addWidget(self.tab3_mouseDelaylineEdit)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.tab3_mouseScreenpushButton = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab3_mouseScreenpushButton.sizePolicy().hasHeightForWidth())
        self.tab3_mouseScreenpushButton.setSizePolicy(sizePolicy)
        self.tab3_mouseScreenpushButton.setObjectName("tab3_mouseScreenpushButton")
        self.horizontalLayout_2.addWidget(self.tab3_mouseScreenpushButton)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.groupBox)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tab3_mouseAddpushButton = QtWidgets.QPushButton(self.widget_9)
        self.tab3_mouseAddpushButton.setObjectName("tab3_mouseAddpushButton")
        self.horizontalLayout_8.addWidget(self.tab3_mouseAddpushButton)
        self.tab3_mouseNamelineEdit = QtWidgets.QLineEdit(self.widget_9)
        self.tab3_mouseNamelineEdit.setObjectName("tab3_mouseNamelineEdit")
        self.horizontalLayout_8.addWidget(self.tab3_mouseNamelineEdit)
        self.tab3_mouseSavepushButton = QtWidgets.QPushButton(self.widget_9)
        self.tab3_mouseSavepushButton.setObjectName("tab3_mouseSavepushButton")
        self.horizontalLayout_8.addWidget(self.tab3_mouseSavepushButton)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 10, 301, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_10 = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_6 = QtWidgets.QWidget(self.widget_10)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.tab3_keyDelaylineEdit = QtWidgets.QLineEdit(self.widget_6)
        self.tab3_keyDelaylineEdit.setObjectName("tab3_keyDelaylineEdit")
        self.horizontalLayout_6.addWidget(self.tab3_keyDelaylineEdit)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.verticalLayout_5.addWidget(self.widget_10)
        self.widget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tab3_keyAddpushButton = QtWidgets.QPushButton(self.widget_7)
        self.tab3_keyAddpushButton.setObjectName("tab3_keyAddpushButton")
        self.horizontalLayout_7.addWidget(self.tab3_keyAddpushButton)
        self.tab3_keyNamelineEdit = QtWidgets.QLineEdit(self.widget_7)
        self.tab3_keyNamelineEdit.setObjectName("tab3_keyNamelineEdit")
        self.horizontalLayout_7.addWidget(self.tab3_keyNamelineEdit)
        self.tab3_keySavepushButton = QtWidgets.QPushButton(self.widget_7)
        self.tab3_keySavepushButton.setObjectName("tab3_keySavepushButton")
        self.horizontalLayout_7.addWidget(self.tab3_keySavepushButton)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 291, 241))
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_11 = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_13 = QtWidgets.QWidget(self.widget_11)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tab3_picPathlineEdit = QtWidgets.QLineEdit(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab3_picPathlineEdit.sizePolicy().hasHeightForWidth())
        self.tab3_picPathlineEdit.setSizePolicy(sizePolicy)
        self.tab3_picPathlineEdit.setReadOnly(True)
        self.tab3_picPathlineEdit.setObjectName("tab3_picPathlineEdit")
        self.horizontalLayout_9.addWidget(self.tab3_picPathlineEdit)
        self.tab3_picOpenpushButton = QtWidgets.QPushButton(self.widget_13)
        self.tab3_picOpenpushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.tab3_picOpenpushButton.setObjectName("tab3_picOpenpushButton")
        self.horizontalLayout_9.addWidget(self.tab3_picOpenpushButton)
        self.verticalLayout_7.addWidget(self.widget_13)
        self.tab3_picShowlabel = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab3_picShowlabel.sizePolicy().hasHeightForWidth())
        self.tab3_picShowlabel.setSizePolicy(sizePolicy)
        self.tab3_picShowlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.tab3_picShowlabel.setScaledContents(True)
        self.tab3_picShowlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tab3_picShowlabel.setObjectName("tab3_picShowlabel")
        self.verticalLayout_7.addWidget(self.tab3_picShowlabel)
        self.verticalLayout_6.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tab3_picAddpushButton = QtWidgets.QPushButton(self.widget_12)
        self.tab3_picAddpushButton.setObjectName("tab3_picAddpushButton")
        self.horizontalLayout_11.addWidget(self.tab3_picAddpushButton)
        self.tab3_picNamelineEdit = QtWidgets.QLineEdit(self.widget_12)
        self.tab3_picNamelineEdit.setObjectName("tab3_picNamelineEdit")
        self.horizontalLayout_11.addWidget(self.tab3_picNamelineEdit)
        self.tab3_picSavepushButton = QtWidgets.QPushButton(self.widget_12)
        self.tab3_picSavepushButton.setObjectName("tab3_picSavepushButton")
        self.horizontalLayout_11.addWidget(self.tab3_picSavepushButton)
        self.verticalLayout_6.addWidget(self.widget_12)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(320, 180, 261, 221))
        self.groupBox_10.setObjectName("groupBox_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setAutoFillBackground(False)
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 26))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动助手 v1.0"))
        self.tab0_hwndlineEdit.setPlaceholderText(_translate("MainWindow", "窗口句柄"))
        self.tab0_bindWinpushButton.setText(_translate("MainWindow", "绑定窗口"))
        self.tab0_showLogpushButton.setText(_translate("MainWindow", "日志查看"))
        self.groupBox_5.setTitle(_translate("MainWindow", "线程明细"))
        self.tab0_threadRefleshpushButton.setText(_translate("MainWindow", "刷新"))
        self.tab0_threadSavepushButton.setText(_translate("MainWindow", "保存"))
        self.tab0_threadAddpushButton.setText(_translate("MainWindow", "新增"))
        self.tab0_threadDelpushButton.setText(_translate("MainWindow", "删除"))
        self.groupBox_4.setTitle(_translate("MainWindow", "所有任务"))
        self.tab0_missionRefleshpushButton.setText(_translate("MainWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "线程管理"))
        self.groupBox_6.setTitle(_translate("MainWindow", "任务明细"))
        self.tab1_missionRefleshpushButton.setText(_translate("MainWindow", "刷新"))
        self.tab1_missionSavepushButton.setText(_translate("MainWindow", "保存"))
        self.tab1_missionAddpushButton.setText(_translate("MainWindow", "新增"))
        self.tab1_missionDelpushButton.setText(_translate("MainWindow", "删除"))
        self.groupBox_7.setTitle(_translate("MainWindow", "所有功能"))
        self.tab1_funRefleshpushButton.setText(_translate("MainWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "任务管理"))
        self.groupBox_8.setTitle(_translate("MainWindow", "功能明细"))
        self.tab2_funRefleshpushButton.setText(_translate("MainWindow", "刷新"))
        self.tab2_funSavepushButton.setText(_translate("MainWindow", "保存"))
        self.tab2_funAddpushButton.setText(_translate("MainWindow", "新增"))
        self.tab2_funDelpushButton.setText(_translate("MainWindow", "删除"))
        self.groupBox_9.setTitle(_translate("MainWindow", "所有节点"))
        self.tab2_nodeRefleshpushButton.setText(_translate("MainWindow", "刷新"))
        self.tab2_nodeDelpushButton.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "功能管理"))
        self.groupBox.setTitle(_translate("MainWindow", "鼠标节点(前台)"))
        self.label_3.setText(_translate("MainWindow", "坐标X"))
        self.tab3_mouseXlineEdit.setPlaceholderText(_translate("MainWindow", "数值"))
        self.label_2.setText(_translate("MainWindow", "坐标Y"))
        self.tab3_mouseYlineEdit.setPlaceholderText(_translate("MainWindow", "数值"))
        self.label_4.setText(_translate("MainWindow", "延迟 "))
        self.tab3_mouseDelaylineEdit.setText(_translate("MainWindow", "1"))
        self.tab3_mouseDelaylineEdit.setPlaceholderText(_translate("MainWindow", "数值"))
        self.tab3_mouseScreenpushButton.setText(_translate("MainWindow", "屏幕取点"))
        self.tab3_mouseAddpushButton.setText(_translate("MainWindow", "新增节点"))
        self.tab3_mouseNamelineEdit.setText(_translate("MainWindow", "鼠标"))
        self.tab3_mouseNamelineEdit.setPlaceholderText(_translate("MainWindow", "节点名称"))
        self.tab3_mouseSavepushButton.setText(_translate("MainWindow", "保存"))
        self.groupBox_2.setTitle(_translate("MainWindow", "按键节点(前台)"))
        self.label_5.setText(_translate("MainWindow", "按键"))
        self.label_6.setText(_translate("MainWindow", "延迟"))
        self.tab3_keyDelaylineEdit.setText(_translate("MainWindow", "1"))
        self.tab3_keyDelaylineEdit.setPlaceholderText(_translate("MainWindow", "数值"))
        self.tab3_keyAddpushButton.setText(_translate("MainWindow", "新增节点"))
        self.tab3_keyNamelineEdit.setText(_translate("MainWindow", "按键"))
        self.tab3_keyNamelineEdit.setPlaceholderText(_translate("MainWindow", "节点名称"))
        self.tab3_keySavepushButton.setText(_translate("MainWindow", "保存"))
        self.groupBox_3.setTitle(_translate("MainWindow", "找图点击节点"))
        self.tab3_picPathlineEdit.setPlaceholderText(_translate("MainWindow", "路径"))
        self.tab3_picOpenpushButton.setText(_translate("MainWindow", "图片"))
        self.tab3_picShowlabel.setText(_translate("MainWindow", "预览图片"))
        self.tab3_picAddpushButton.setText(_translate("MainWindow", "新增节点"))
        self.tab3_picNamelineEdit.setText(_translate("MainWindow", "找图"))
        self.tab3_picNamelineEdit.setPlaceholderText(_translate("MainWindow", "节点名称"))
        self.tab3_picSavepushButton.setText(_translate("MainWindow", "保存"))
        self.groupBox_10.setTitle(_translate("MainWindow", "屏幕取色节点"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "节点配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "系统配置"))
